labeled_data: true
seperate_labels: false
test_train_split: true
split_value: '0.25'
current_data_file: C:/Users/steph/OneDrive/Documents/GitHub/SensorAiFramework/data/demo_data.npy
current_label_file: ''
current_log_file: ''
